### ISSUE TITLE
update mining claims in package

### ISSUE THREAD

**Issue by mvisalli** [ecoquants/bbnj#14]
@bbest new mining claim shapefiles (ISA_claim_areas_20190719) are in [google drive](https://drive.google.com/drive/u/0/folders/1YQSsGYyqcUjWC96RmEKCwd_eTKtE-n6r)

**Comment by mvisalli** [comment]
@bbest sorry I just realized that the APEI (Areas of Particular Environmental Interest) areas are also included in that mining claim shapefile. I think we should remove those before calculating % overlap with mining claims because APEIs are more like protected areas

**Comment by bbest** [comment]
No prob. Did same for previous. It's now loaded per https://github.com/ecoquants/bbnj/commit/b312aec79142c4371ba1aab13ab47de606a9d330
