### ISSUE TITLE
create separate folder for old scenario experiments

### ISSUE THREAD

**Issue by mvisalli** [ecoquants/bbnj#15]
inst/app/www/scenarios is getting pretty crazy! Could we create another folder somewhere to house old scenario experiments?

**Comment by mvisalli** [comment]
On my local copy I created a subfolder `inst/app/www/scenarios/experiments` where I moved the older scenario experiments that are now less relevant (but we may at some point want to refer back to). I've kept all of our latest scenario iterations in `inst/app/www/scenarios`

@bbest let me know if you think this will mess up the mapper and I can revert or move the experiments folder elsewhere

**Comment by bbest** [comment]
I agree it's getting pretty crazy in `inst/app/www/scenarios/experiments`. At the moment the mapper just looks directly in the `inst/app/www/scenarios` folder, not recursively in subfolders so your solution shouldn't break things. I slightly prefer `archive` over `experiments`. 

I could have it look recursively in subfolders of `scenarios` and prefix the label on the dropdown accordingly.

Bigger picture, am thinking of overhauling the mapper as outlined here:

* [overhaul mapper · Issue #16 · ecoquants/bbnj](https://github.com/ecoquants/bbnj/issues/16)
* [deploy mapper on hosted Amazon server · Issue #17 · ecoquants/bbnj](https://github.com/ecoquants/bbnj/issues/17)
