### ISSUE TITLE
fix taxonomic groupings

### ISSUE THREAD

**Issue by bbest** [ecoquants/bbnj#3]
Per meeting _**2019-07-03 BB, MG**_ w/ @mvisalli in [notes | bbnj - Google Docs](https://docs.google.com/document/d/1wkYA9_MAD1SN0w62jfp9a_1nz5-xgNQTZnY7PZi0KTs/edit#heading=h.1hz4fkybxtb3):

Currently of 24,904 species (before masking out high seas),  group is NA for 1,176.

- ∆ **Cetaceans**:
  ```r
  # old:
  Order == "Artiodactyla" ~ "Cetaceans",
  # new:
  Order == "Cetacea" ~ "Cetaceans",
  ```
- ∆ **Squids**:
  ```r
  # old:
  Order %in% c("Myopsida","Oegopsida")
  # new:
  Order %in% c("Myopsida","Oegopsida","Teuthida")
  ```
-  ∆ **Sharks** → **Sharks & Rays**
- ∆ **Worms**:
  ```r
  # old
  Phylum == "Annelida"
  # new
  Phylum %in% c("Annelida", "Sipuncula")
  ```
- **+ Forams**:
  ```r
  Phylum == "Foraminifera"
  ```

## to consider

From Morgan's notes:

- Two other classes of Phylum [Mollusca](https://en.wikipedia.org/wiki/Mollusca#Classification)? 
  - Class [Aplacophora](https://en.wikipedia.org/wiki/Aplacophora) (shell-less molluscs)
  - Class [Scaphopoda](https://en.wikipedia.org/wiki/Tusk_shell) (tusk shells)
- Any of these?
  - Phylum Chordata: (Sub)Class [Holocephali](https://en.wikipedia.org/wiki/Holocephali) ("complete heads" fish)
  - Phylum Chordata: Class [Myxini](https://en.wikipedia.org/wiki/Hagfish) (hagfish)
  - Phylum [Cnidaria](https://en.wikipedia.org/wiki/Cnidaria): Class [Scyphozoa](https://en.wikipedia.org/wiki/Scyphozoa) (jellyfish)
- Do we want to pull out green algae (Phylum [Chlorophyta](https://en.wikipedia.org/wiki/Chlorophyta)) or red algae (Phylum [Rhodophyta](https://en.wikipedia.org/wiki/Red_algae))? They’re currently captured by NA

## species data and groupings

* **Assign Taxonomic Groups** in [Calculate Indicators • gmbi](https://marinebon.github.io/gmbi/articles/calc.html#assign-taxonomic-groups): assignment performed here

  * [marinebon/gmbi: inst/data/`spp.csv`](https://raw.githubusercontent.com/marinebon/gmbi/master/inst/data/spp.csv)
  * [spp.xlsx - Google Drive](https://drive.google.com/file/d/1EPvjoEgSTMn85A4c9Yyqjd9agO49yVju/view)

## References: basis of taxonomic groupings

* Tittensor et al. (2010) [Global patterns and predictors of marine biodiversity across taxa | Nature](https://www.nature.com/articles/nature09329)
* Selig et al. (2013) [Assessing Global Marine Biodiversity Status within a Coupled Socio-Ecological Perspective](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0060284)
* [Spatial Data Download: IUCN Red List of Threatened Species](https://www.iucnredlist.org/resources/spatial-data-download)
* Fautin et al (2010) [An Overview of Marine Biodiversity in United States Waters](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2914028/)

**Comment by bbest** [comment]
made taxa changes above in [marinebon/gmbi:vignettes/calc.Rmd](https://github.com/marinebon/gmbi/commit/6900e79246eeace17f1e1e7693676e0dcbbcb268#diff-c8bbee0dcce5adcf7d7492f7ad704381), but need to still run script and update gmbi + bbnj repos

**Comment by bbest** [comment]
For others, see https://github.com/marinebon/gmbi/issues/1

**Comment by mvisalli** [comment]
I believe that the taxonomic breakdown I used for the treemap reflects the changes suggested by Doug and referenced in [marinebon/gmbi#1](https://github.com/marinebon/gmbi/issues/1) (i.e. group all cephalopods instead of breaking out squid, changing coastal fishes to bony fishes, and removing forams group)

https://github.com/ecoquants/bbnj/blob/6ce535a3c3e558e59c2557a2cbb17f8503fe3d95/inst/scripts/spp_treemap.Rmd#L36-L56

**Comment by mvisalli** [comment]
@bbest Doug and I spoke last night and came up w proposed taxonomic clumping for 9 groups:

Invert
Bony fishes
Marine Mammals
Corals
Cephalopods
Seagrasses
Sharks & rays
Tunas & billfishes
Other

How does that look to you? If ok, I can copy the code from gmbi where you define taxonomic groups and modify to reflect this breakdown & send you updated code to plug in -- is that helpful?

**Comment by mvisalli** [comment]
Code for updating taxonomic clumping here:
https://github.com/ecoquants/bbnj/blob/3765f44f41d503ea9c5ceb15b9406b128f624199/inst/scripts/spp_treemap_DJM.Rmd#L36-L43

**Comment by bbest** [comment]
TODO: get map app to show all taxonomic groups##

**Comment by mvisalli** [comment]
**Low** priority items (especially since @bbest just re-ran this -- sorry!):

- **Tunicates:** add class **Appendicularia** to group **Tunicates**
- **Cephalopods:** confirm that **Teuthida** is actually captured in group **Non-Squid Cephalopods** and change name of group to Cephalopods (or just change code to  `Class == "Cephalopoda" ~ "Cephalopods"`)
- **Jellyfish:** **Hydrozoa** are currently pulled out in their own group, but I think other jellyfish are captured in the group **Other**. We could consider creating a Jellyfish group to include all members of [Medusozoa subphylum](https://en.wikipedia.org/wiki/Medusozoa) which would include the following classes:
Cubozoa – box jellyfish
Hydrozoa – hydrozoans
Scyphozoa – true jellyfish
Staurozoa – stalked jellyfish

**Comment by bbest** [comment]
Hi @mvisalli,

Just to confirm this edit:

- **Cephalopods:** confirm that **Teuthida** is actually captured in group **Non-Squid Cephalopods** and change name of group to Cephalopods (or just change code to  `Class == "Cephalopoda" ~ "Cephalopods"`)

Do you mean, make sure that **Teuthida** is actively excluded (`!Order %in%`) from  **Cephalopods** and included (`Order %in%`) in **Squids** per [Squid | Wikipedia](https://en.wikipedia.org/wiki/Squid)?

- **Cephalopods**
  `Class == "Cephalopoda" & !Order %in% c("Myopsida","Oegopsida","Teuthida")`
- **Squids**
  `Order %in% c("Myopsida","Oegopsida","Teuthida")`

This was in the code but not the markdown documentation. I'm applying the rest of the fixes to `groups01` (+ `groups02` & `groups03`).

**Comment by mvisalli** [comment]
Hi @bbest,

It was my understanding that we wanted to include Squid in the group Cephalopods rather than breaking out into "Squids" and "Non-Squid Cephalopods." Does that sounds ok to you?
