### ISSUE TITLE
tally species per taxa after masking for high seas

### ISSUE THREAD

**Issue by bbest** [ecoquants/bbnj#5]
Best way to do this is by calculating percent of species distribution (probability > 0.5) in the high seas, so could filter to species with at least 25% of their distribution on the high seas (a la GreenPeace report).

This will have to happen within the AquaMaps database per [Calculate Indicators • gmbi](https://marinebon.github.io/gmbi/articles/calc.html), and then ideally becomes another column in [gmbi:inst/data/`spp.csv`](https://github.com/marinebon/gmbi/blob/master/inst/data/spp.csv) which should get added to bbnj as a species dataset along with [bbnj:datasets](http://ecoquants.com/bbnj/reference/index.html#section-datasets).

**Comment by mvisalli** [comment]
After filtering for for species with at least 25% of their distribution in the high seas, will we need to create new layers for nspp_all and nspp for each taxonomic group?

I wonder if applying the 25% distribution in high seas filter would end up removing a bunch of species that may usually be coastal but show up in unique shallow areas like Mascarene Plateau

**Comment by bbest** [comment]
Here's the number of species by percentage area in the high seas:

%hs  |    ~0    | ~0-25% |  25-100% 
-----|--------|---------|--------
#spp |   13,331  |   9,516   | 2,051 
%spp |    53.5%   |  38.2% |    8.2%

Here's the breakdown by taxonomic group in case we want to rethink these before proceeding. Mangroves and Seagrasses get dropped for instance. Do we want to lump Forams into NA, which we can call Other?

#### Table. Number of  species by % area in high seas of ocean area (given by probability >= 0.5)
group | (NA) | ~0 | <=0.25% | > 25% | n group | %n > 25% | %N > 25%
--|--|--|--|--|--|--|--
Bivalves |   | 578 | 428 | 12 | 1,018 | 1% | 0.6%
Bony fishes | 3 | 6,433 | 3,648 | 1,325 | 11,409 | 12% | 64.6%
Cetaceans |   | 14 | 16 | 52 | 82 | 63% | 2.5%
Chitons |   | 62 | 18 | 1 | 81 | 1% | 0.0%
Corals |   | 489 | 419 | 10 | 918 | 1% | 0.5%
Crustaceans | 1 | 1,232 | 1,650 | 175 | 3,058 | 6% | 8.5%
Echinoderms | 2 | 532 | 389 | 33 | 956 | 3% | 1.6%
Euphausiids |   | 8 | 34 | 1 | 43 | 2% | 0.0%
Forams |   | 11 | 3 | 2 | 16 | 13% | 0.1%
Gastropods |   | 1,952 | 848 | 52 | 2,852 | 2% | 2.5%
Hydrozoans |   | 79 | 233 | 9 | 321 | 3% | 0.4%
Mangroves |   | 1 | - | - | 1 | 0% | 0.0%
Non-squid cephalopods |   | 149 | 113 | 33 | 295 | 11% | 1.6%
Pinnipeds |   | 7 | 17 | 8 | 32 | 25% | 0.4%
Reptiles |   | 20 | 13 | 1 | 34 | 3% | 0.0%
Sea spiders |   | 119 | 149 | 64 | 332 | 19% | 3.1%
Seagrasses |   | 7 | 3 | - | 10 | 0% | 0.0%
Sharks & rays | 2 | 448 | 335 | 49 | 834 | 6% | 2.4%
Sponges |   | 315 | 116 | 9 | 440 | 2% | 0.4%
Tunas & billfishes |   | 24 | 18 | 21 | 63 | 33% | 1.0%
Tunicates | 1 | 225 | 344 | 84 | 654 | 13% | 4.1%
Worms |   | 166 | 239 | 46 | 451 | 10% | 2.2%
NA |   | 458 | 482 | 64 | 1,004 | 6% | 3.1%
N TOTAL | 9 | 13,329 | 9,515 | 2,051 | 24,904 |   | 100%

![image](https://user-images.githubusercontent.com/2837257/61609029-aa19a000-ac09-11e9-9d18-ed8b08e9030f.png)

Here are the files for tables above:

* [marinebon/gmbi: inst/data/spp_bbnj.csv](https://github.com/marinebon/gmbi/blob/2a3c4bfeb8da717311ddd1fbbdd6deab26bb8cdb/inst/data/spp_bbnj.csv)
* [marinebon/gmbi: inst/data/spp_bbnj_grouped.xls](https://github.com/marinebon/gmbi/blob/2a3c4bfeb8da717311ddd1fbbdd6deab26bb8cdb/inst/data/spp_bbnj_grouped.xls)
* [marinebon/gmbi: inst/data/spp_bbnj_grouped.csv](https://github.com/marinebon/gmbi/blob/2a3c4bfeb8da717311ddd1fbbdd6deab26bb8cdb/inst/data/spp_bbnj_grouped.csv)

**Comment by bbest** [comment]
Hi @mvisalli,

Here's the updated summary of species revised to include **Antarctica** in the high seas...

%hs | ~0 | ~0-25% | 25-100%
-- | -- | -- | --
#spp | 13,217 | 9,008 | 2,673
%spp | 53.1% | 36.2% | 10.7%

And here's the individual species association with groups and in/out high seas:

marinebon/gmbi: [spp_bbnj.csv](
https://github.com/marinebon/gmbi/blob/44ef97eae5d464a8489e242a8cf3420bf2ee89f3/inst/data/spp_bbnj.csv)

I haven't yet summarized like above https://github.com/ecoquants/bbnj/issues/5#issuecomment-513649535.

**Comment by mvisalli** [comment]
Yayyy! Thanks @bbest ! When I re-run the treemap script I end up with 12,013 species in HS (by counting number of species in group 2). Where is the 13,217 spp coming from?
