### ISSUE TITLE
Fix Se

### ISSUE THREAD

**Issue by bbest** [ecoquants/bbnj#7]
Good eye @mvisalli at catching the inconsistency between the layer values in the provided Harris and Whiteway (2009) `class_11` ArcGIS raster vs. manuscript version.

## raster

dir: `/Users/bbest/Gdrive Ecoquants/projects/bbnj/data/raw/Harris and Whiteway 2009/Global_Seascapes/`:
- `class_11`
- `Global Seascape 11 class classification.lyr`

Looking at this in ArcGIS Pro...

![image](https://user-images.githubusercontent.com/2837257/61235525-92fb1f80-a6ea-11e9-82ae-47f4fea5ddf3.png)

![image](https://user-images.githubusercontent.com/2837257/61235275-00f31700-a6ea-11e9-8e74-9f9f67781b6b.png)

Global Seascape 11 class classification
Seascape Class
1. Very deep, very flat very cold, moderate dissolved oxygen, very thin sediment, very low primary production
2. Very deep, very flat, very cold, high dissolved oxygen, very thin sediment, low primary production
3. Deep, very flat, very cold, moderate dissolved oxygen, very thin sediment, low primary production
4. Deep, flat, very cold, high dissolved oxygen, very thin sediment, low primary production
5. Very deep, moderate slope, very cold, moderate dissolved oxygen, very thin sediment, very low primary production
6. Deep, very steep, very cold, moderate dissolved oxygen, very thin sediment, low primary production
7. Moderate depth, flat, cold, moderate dissolved oxygen, thick sediment, moderate primary production
8. Moderate depth, moderate slope, cold, very low dissolved oxygen, thin sediment, very low primary production
9. Shallow, flat, cold, very high dissolved oxygen, thin sediment, high primary production
10. Very shallow, moderate slope, very warm, very low dissolved oxygen, moderate sediment, high primary production
11. Moderate depth, steep, cold, high dissolved oxygen thin sediment moderate primary production

## manuscript

![image](https://user-images.githubusercontent.com/2837257/61235623-ca69cc00-a6ea-11e9-8a1b-68e365c16afc.png)

Legend

EEZ of the World
1. Upper Bathyal, shallow shelf, low DO, very high PP, thick sediment, very warm
2. Lower Bathyal, deep shelf (submerged), marginal plateaus, very high DO, high PP, thick sediment, warm
3. Lower Bathyal, other ridges and plateaus, marginal plateaus, marginal seas with hilly bottom, steep, very low DO
4. Lower Bathyal, continental slope, steep, high PP. very thick sediment, warm
5. Lower Bathyal, island arcs, steep, high DO
6. Lower Bathyal (Abyssal-Hadal), deep water trenches, island arcs, trenches controlled by fracture zones, volcanic ridges and plateaus, very steep
7. Abyssal, volcanic ridges and highs, central rift zone, ridge flanks, microcontinents, cold
8. Abyssal, flat sedimented plains of marginal seas, central rift zone, ridge flanks, marginal seas with hilly bottoms, flat, low DO, thin sediment
9. Abyssal (Hadal), trenches controlled by fracture zones, deep water trenches, large arched uplifted structures low PP. thin sediment, cold
10. Abyssal, plains with slightly undulating seafloor, fiat abyssal plains, continental rise, very flat, high DO. low PP, very cold
11. Abyssal, hilly plains, large (arched) uplifted structures, flat abyssal plains, flat, very low PP, very thin sediment.

**Comment by bbest** [comment]
This fix to the classification shouldn't affect analytical results thus far, just the dataset documentation (and interpretation) which can be updated here:

* [bbnj/data.R at master · ecoquants/bbnj](https://github.com/ecoquants/bbnj/blob/6ce535a3c3e558e59c2557a2cbb17f8503fe3d95/R/data.R#L169-L189)

which after running `devtools::document()` updates the documentation here:

* [Raster stack for area (km2) of 1 thru 11 classes of benthic seascapes (Harris & Whiteway, 2009) — s_phys_scapes • bbnj](http://ecoquants.com/bbnj/reference/s_phys_scapes.html)

**Comment by mvisalli** [comment]
Updated documentation within R, but not html page: http://ecoquants.com/bbnj/reference/s_phys_scapes.html

@bbest
