### ISSUE TITLE
error when trying to run scenario

### ISSUE THREAD

**Issue by mvisalli** [ecoquants/bbnj#8]
I think something is up with my working directory, when I run:
https://github.com/ecoquants/bbnj/blob/bc0fdde55517317a194634adb8f9c213d41b70aa/inst/app/www/scenarios/s00a.bio.30pct.gl.gcs0.5d.Rmd#L29-L31

I receive the error:

> Error in dirname(path[!is_missing]) : 
>   a character vector argument expected

Tried a few things but no luck yet. Any ideas @bbest ?

**Comment by mvisalli** [comment]
Nevermind, I realized that 

https://github.com/ecoquants/bbnj/blob/bc0fdde55517317a194634adb8f9c213d41b70aa/inst/app/www/scenarios/s00a.bio.30pct.gl.gcs0.5d.Rmd#L29-L31

will only work when I knit the document. However now having issue where scenario map doesn't render in html output. Sorry if I'm jumping the gun here!

**Comment by bbest** [comment]
Hi @mvisalli,

The rendering should work again (and now in 300 dpi) after reinstalling. I moved things around a bit in the latest scenario `s00a.bio.30pct.gl.mol50km.Rmd`
